
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.2/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.26200 - AMD64
  -
    kind: "find-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.2/Modules/CMakeDetermineCompilerId.cmake:462 (find_file)"
      - "C:/Program Files/CMake/share/cmake-4.2/Modules/CMakeDetermineCompilerId.cmake:500 (CMAKE_DETERMINE_COMPILER_ID_WRITE)"
      - "C:/Program Files/CMake/share/cmake-4.2/Modules/CMakeDetermineCompilerId.cmake:8 (CMAKE_DETERMINE_COMPILER_ID_BUILD)"
      - "C:/Program Files/CMake/share/cmake-4.2/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-4.2/Modules/CMakeDetermineCSharpCompiler.cmake:23 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    mode: "file"
    variable: "src_in"
    description: "Path to a file."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "CMakeCSharpCompilerId.cs.in"
    candidate_directories:
      - "C:/Program Files/CMake/share/cmake-4.2/Modules/"
    found: "C:/Program Files/CMake/share/cmake-4.2/Modules/CMakeCSharpCompilerId.cs.in"
    search_context:
      ENV{PATH}:
        - "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX64\\x64"
        - "C:\\VulkanSDK\\1.4.341.1\\Bin"
        - "C:\\Program Files\\Oculus\\Support\\oculus-runtime"
        - "C:\\VulkanSDK\\1.4.328.1\\Bin"
        - "C:\\Windows\\system32"
        - "C:\\Windows"
        - "C:\\Windows\\System32\\Wbem"
        - "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\"
        - "C:\\Windows\\System32\\OpenSSH\\"
        - "C:\\Program Files\\Git\\cmd"
        - "C:\\Program Files\\Microsoft VS Code\\bin"
        - "C:\\Program Files\\dotnet\\"
        - "C:\\Program Files (x86)\\Windows Kits\\10\\Windows Performance Toolkit\\"
        - "C:\\Program Files\\CMake\\bin"
        - "C:\\Program Files\\Neovim\\bin"
        - "C:\\Program Files\\NVIDIA Corporation\\NVIDIA App\\NvDLISR"
        - "C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common"
        - "C:\\Program Files\\nodejs\\"
        - "C:\\Users\\kekli\\AppData\\Local\\Microsoft\\WindowsApps"
        - "C:\\Users\\kekli\\AppData\\Local\\GitHubDesktop\\bin"
        - "C:\\mingw64\\bin"
        - "C:\\MinGW"
        - "C:\\MinGW\\bin"
        - "C:\\Users\\kekli\\.dotnet\\tools"
        - "C:\\Users\\kekli\\AppData\\Roaming\\npm"
        - "C:\\Users\\kekli\\AppData\\Local\\Microsoft\\WinGet\\Packages\\Google.DartSDK_Microsoft.Winget.Source_8wekyb3d8bbwe\\dart-sdk\\bin"
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.2/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-4.2/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-4.2/Modules/CMakeDetermineCSharpCompiler.cmake:23 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CSharp compiler identification source file "CMakeCSharpCompilerId.cs" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      MSBuild version 17.14.23+b0019275e for .NET Framework
      Build started 4/28/2026 12:10:14 AM.
      
      Project "F:\\Github\\GlassEngine\\out\\build\\x64-debug\\Editor\\projects\\sandbox\\Intermediates\\CMakeFiles\\4.2.0-rc2\\CompilerIdCSharp\\CompilerIdCSharp.csproj" on node 1 (default targets).
      PrepareForBuild:
        Creating directory "obj\\x64\\Debug\\".
      CoreCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Current\\Bin\\Roslyn\\csc.exe /noconfig /nowarn:1701,1702 /fullpaths /nostdlib+ /platform:anycpu32bitpreferred /define:Platformx64;PlatformToolsetv143 /highentropyva+ /reference:"C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.7.2\\mscorlib.dll" /reference:"C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.7.2\\System.Core.dll" /debug+ /out:obj\\x64\\Debug\\CompilerIdCSharp.exe /subsystemversion:6.00 /target:exe /utf8output /langversion:7.3 CMakeCSharpCompilerId.cs "obj\\x64\\Debug\\.NETFramework,Version=v4.7.2.AssemblyAttributes.cs"
        CompilerServer: server - server processed compilation - CompilerIdCSharp
      CopyFilesToOutputDirectory:
        Copying file from "F:\\Github\\GlassEngine\\out\\build\\x64-debug\\Editor\\projects\\sandbox\\Intermediates\\CMakeFiles\\4.2.0-rc2\\CompilerIdCSharp\\obj\\x64\\Debug\\CompilerIdCSharp.exe" to "F:\\Github\\GlassEngine\\out\\build\\x64-debug\\Editor\\projects\\sandbox\\Intermediates\\CMakeFiles\\4.2.0-rc2\\CompilerIdCSharp\\CompilerIdCSharp.exe".
        CompilerIdCSharp -> F:\\Github\\GlassEngine\\out\\build\\x64-debug\\Editor\\projects\\sandbox\\Intermediates\\CMakeFiles\\4.2.0-rc2\\CompilerIdCSharp\\CompilerIdCSharp.exe
        Copying file from "F:\\Github\\GlassEngine\\out\\build\\x64-debug\\Editor\\projects\\sandbox\\Intermediates\\CMakeFiles\\4.2.0-rc2\\CompilerIdCSharp\\obj\\x64\\Debug\\CompilerIdCSharp.pdb" to "F:\\Github\\GlassEngine\\out\\build\\x64-debug\\Editor\\projects\\sandbox\\Intermediates\\CMakeFiles\\4.2.0-rc2\\CompilerIdCSharp\\CompilerIdCSharp.pdb".
      PostBuildEvent:
        if not "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Current\\Bin\\Roslyn"=="" if exist "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Current\\Bin\\Roslyn\\csc.exe" set _CSC=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Current\\Bin\\Roslyn
        if exist "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Current\\Bin\\amd64\\csc.exe" set _CSC=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Current\\Bin\\amd64
        if "%_CSC%"=="" exit -1
        @echo CMAKE_CSharp_COMPILER=%_CSC%\\csc.exe
        CMAKE_CSharp_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Current\\Bin\\Roslyn\\csc.exe
      Done Building Project "F:\\Github\\GlassEngine\\out\\build\\x64-debug\\Editor\\projects\\sandbox\\Intermediates\\CMakeFiles\\4.2.0-rc2\\CompilerIdCSharp\\CompilerIdCSharp.csproj" (default targets).
      
      Build succeeded.
          0 Warning(s)
          0 Error(s)
      
      Time Elapsed 00:00:00.22
      
      
      Compilation of the CSharp compiler identification source "CMakeCSharpCompilerId.cs" produced "CompilerIdCSharp.csproj"
      
      Compilation of the CSharp compiler identification source "CMakeCSharpCompilerId.cs" produced "CompilerIdCSharp.exe"
      
      Compilation of the CSharp compiler identification source "CMakeCSharpCompilerId.cs" produced "CompilerIdCSharp.pdb"
      
      The CSharp compiler identification could not be found in:
        F:/Github/GlassEngine/out/build/x64-debug/Editor/projects/sandbox/Intermediates/CMakeFiles/4.2.0-rc2/CompilerIdCSharp/CompilerIdCSharp.csproj
      
      The CSharp compiler identification is Microsoft Visual Studio, found in:
        F:/Github/GlassEngine/out/build/x64-debug/Editor/projects/sandbox/Intermediates/CMakeFiles/4.2.0-rc2/CompilerIdCSharp/CompilerIdCSharp.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.2/Modules/CMakeTestCSharpCompiler.cmake:34 (try_compile)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Check for working C# compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/Roslyn/csc.exe"
    directories:
      source: "F:/Github/GlassEngine/out/build/x64-debug/Editor/projects/sandbox/Intermediates/CMakeFiles/CMakeScratch/TryCompile-9uxsug"
      binary: "F:/Github/GlassEngine/out/build/x64-debug/Editor/projects/sandbox/Intermediates/CMakeFiles/CMakeScratch/TryCompile-9uxsug"
    cmakeVariables:
      CMAKE_CSharp_FLAGS: "/platform:x64 /define:TRACE"
      CMAKE_CSharp_FLAGS_DEBUG: "/debug:full /optimize- /warn:3 /errorreport:prompt /define:DEBUG"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_CSharp_COMPILER_WORKS"
      cached: true
      stdout: |
        Change Dir: 'F:/Github/GlassEngine/out/build/x64-debug/Editor/projects/sandbox/Intermediates/CMakeFiles/CMakeScratch/TryCompile-9uxsug'
        
        Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_57901.csproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        MSBuild version 17.14.23+b0019275e for .NET Framework
        Build started 4/28/2026 12:10:15 AM.
        
        Project "F:\\Github\\GlassEngine\\out\\build\\x64-debug\\Editor\\projects\\sandbox\\Intermediates\\CMakeFiles\\CMakeScratch\\TryCompile-9uxsug\\cmTC_57901.csproj" on node 1 (default targets).
        PrepareForBuild:
          Creating directory "F:\\Github\\GlassEngine\\out\\build\\x64-debug\\Editor\\projects\\sandbox\\Intermediates\\CMakeFiles\\CMakeScratch\\TryCompile-9uxsug\\Debug\\".
          Creating directory "obj\\x64\\Debug\\".
        CoreCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Current\\Bin\\Roslyn\\csc.exe /noconfig /nowarn:1701,1702 /fullpaths /nostdlib+ /platform:x64 /errorreport:prompt /warn:3 /define:TRACE;DEBUG /highentropyva+ /reference:"C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.7.2\\mscorlib.dll" /reference:"C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.7.2\\System.Core.dll" /debug+ /debug:full /optimize- /out:obj\\x64\\Debug\\cmTC_57901.exe /subsystemversion:6.00 /target:exe /utf8output /langversion:7.3 F:\\Github\\GlassEngine\\out\\build\\x64-debug\\Editor\\projects\\sandbox\\Intermediates\\CMakeFiles\\CMakeScratch\\TryCompile-9uxsug\\testCSharpCompiler.cs "obj\\x64\\Debug\\.NETFramework,Version=v4.7.2.AssemblyAttributes.cs"
          CompilerServer: server - server processed compilation - cmTC_57901
        CopyFilesToOutputDirectory:
          Copying file from "F:\\Github\\GlassEngine\\out\\build\\x64-debug\\Editor\\projects\\sandbox\\Intermediates\\CMakeFiles\\CMakeScratch\\TryCompile-9uxsug\\obj\\x64\\Debug\\cmTC_57901.exe" to "F:\\Github\\GlassEngine\\out\\build\\x64-debug\\Editor\\projects\\sandbox\\Intermediates\\CMakeFiles\\CMakeScratch\\TryCompile-9uxsug\\Debug\\cmTC_57901.exe".
          cmTC_57901 -> F:\\Github\\GlassEngine\\out\\build\\x64-debug\\Editor\\projects\\sandbox\\Intermediates\\CMakeFiles\\CMakeScratch\\TryCompile-9uxsug\\Debug\\cmTC_57901.exe
          Copying file from "F:\\Github\\GlassEngine\\out\\build\\x64-debug\\Editor\\projects\\sandbox\\Intermediates\\CMakeFiles\\CMakeScratch\\TryCompile-9uxsug\\obj\\x64\\Debug\\cmTC_57901.pdb" to "F:\\Github\\GlassEngine\\out\\build\\x64-debug\\Editor\\projects\\sandbox\\Intermediates\\CMakeFiles\\CMakeScratch\\TryCompile-9uxsug\\Debug\\cmTC_57901.pdb".
        Done Building Project "F:\\Github\\GlassEngine\\out\\build\\x64-debug\\Editor\\projects\\sandbox\\Intermediates\\CMakeFiles\\CMakeScratch\\TryCompile-9uxsug\\cmTC_57901.csproj" (default targets).
        
        Build succeeded.
            0 Warning(s)
            0 Error(s)
        
        Time Elapsed 00:00:00.19
        
      exitCode: 0
...
